services:
  - type: web
    name: constitution-vibes-podcast
    env: python
    buildCommand: |
      cd frontend && npm install && npm run build
    startCommand: gunicorn app:app
    plan: free
    region: oregon
